/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cat.uvic.teknos.m09;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args)
    {
        var dummy = new Dummy();

        dummy.printSomething1();
        dummy.printSomething2();
        dummy.printSomething3();

        System.out.println("The end");
    }
}
